### ISSUE TITLE
Top_P issue in newest project

### ISSUE THREAD

**Issue by nephilimbin** [X-T-E-R/TTS-for-GPT-soVITS#10]
Top_P seems to have been removed .  Please check it 289 line of inference_core.py

**Comment by X-T-E-R** [comment]
Hello, but the original project this project depends on has also supported the DPO option after February 17th (supporting parameters such as top_p, top_k, etc.). For details, please see around line 400 of https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/inference_webui.py. The error you're encountering is very likely because you haven't updated the original project (specifically referring to the AR library inside).你好，但是这个项目依赖的原始项目在2月17日之后也支持了DPO选项（支持参数如top_p、top_k等）。具体细节，请参见https://github.com/RVC-Boss/GPT-SoVITS/blob/main/GPT_SoVITS/inference_webui.py的大约400行。你遇到的错误很可能是因为你没有更新原始项目（特别是指里面的AR库）。

**Comment by nephilimbin** [comment]
Thanks
